/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as AuthedMemoriesIndexRouteImport } from './routes/_authed/memories/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedMemoriesNewIndexRouteImport } from './routes/_authed/memories/new/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/_public/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMemoriesIndexRoute = AuthedMemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMemoriesNewIndexRoute = AuthedMemoriesNewIndexRouteImport.update({
  id: '/memories/new/',
  path: '/memories/new/',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof PublicSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/memories/': typeof AuthedMemoriesIndexRoute
  '/memories/new/': typeof AuthedMemoriesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof PublicSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/memories': typeof AuthedMemoriesIndexRoute
  '/memories/new': typeof AuthedMemoriesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_public/sign-in': typeof PublicSignInRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/memories/': typeof AuthedMemoriesIndexRoute
  '/_authed/memories/new/': typeof AuthedMemoriesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/api/auth/$' | '/memories/' | '/memories/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/api/auth/$' | '/memories' | '/memories/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_public/sign-in'
    | '/api/auth/$'
    | '/_authed/memories/'
    | '/_authed/memories/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicSignInRoute: typeof PublicSignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/memories/': {
      id: '/_authed/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof AuthedMemoriesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/memories/new/': {
      id: '/_authed/memories/new/'
      path: '/memories/new'
      fullPath: '/memories/new/'
      preLoaderRoute: typeof AuthedMemoriesNewIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedMemoriesIndexRoute: typeof AuthedMemoriesIndexRoute
  AuthedMemoriesNewIndexRoute: typeof AuthedMemoriesNewIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedMemoriesIndexRoute: AuthedMemoriesIndexRoute,
  AuthedMemoriesNewIndexRoute: AuthedMemoriesNewIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicSignInRoute: PublicSignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
