/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known/$'
import { Route as PublicConsentRouteImport } from './routes/_public/consent'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as McpIndexRouteImport } from './routes/mcp/index'
import { Route as AuthedConnectionsIndexRouteImport } from './routes/_authed/connections/index'
import { Route as AuthedMemoriesIndexRouteImport } from './routes/_authed/memories/index'
import { Route as AuthedNotesUiTestSplatRouteImport } from './routes/_authed/notes-ui-test/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLogosSlugRouteImport } from './routes/api/logos/$slug'
import { Route as AuthedMemoriesMemory_idIndexRouteImport } from './routes/_authed/memories/$memory_id/index'
import { Route as AuthedMemoriesNewIndexRouteImport } from './routes/_authed/memories/new/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicConsentRoute = PublicConsentRouteImport.update({
  id: '/_public/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/_public/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedConnectionsIndexRoute = AuthedConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedMemoriesIndexRoute = AuthedMemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedNotesUiTestSplatRoute = AuthedNotesUiTestSplatRouteImport.update({
  id: '/notes-ui-test/$',
  path: '/notes-ui-test/$',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogosSlugRoute = ApiLogosSlugRouteImport.update({
  id: '/api/logos/$slug',
  path: '/api/logos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMemoriesMemory_idIndexRoute =
  AuthedMemoriesMemory_idIndexRouteImport.update({
    id: '/memories/$memory_id/',
    path: '/memories/$memory_id/',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedMemoriesNewIndexRoute = AuthedMemoriesNewIndexRouteImport.update({
  id: '/memories/new/',
  path: '/memories/new/',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/consent': typeof PublicConsentRoute
  '/sign-in': typeof PublicSignInRoute
  '/mcp/': typeof McpIndexRoute
  '/notes-ui-test/$': typeof AuthedNotesUiTestSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logos/$slug': typeof ApiLogosSlugRoute
  '/connections/': typeof AuthedConnectionsIndexRoute
  '/memories/': typeof AuthedMemoriesIndexRoute
  '/memories/$memory_id/': typeof AuthedMemoriesMemory_idIndexRoute
  '/memories/new/': typeof AuthedMemoriesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/consent': typeof PublicConsentRoute
  '/sign-in': typeof PublicSignInRoute
  '/mcp': typeof McpIndexRoute
  '/notes-ui-test/$': typeof AuthedNotesUiTestSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logos/$slug': typeof ApiLogosSlugRoute
  '/connections': typeof AuthedConnectionsIndexRoute
  '/memories': typeof AuthedMemoriesIndexRoute
  '/memories/$memory_id': typeof AuthedMemoriesMemory_idIndexRoute
  '/memories/new': typeof AuthedMemoriesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/_public/consent': typeof PublicConsentRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/mcp/': typeof McpIndexRoute
  '/_authed/notes-ui-test/$': typeof AuthedNotesUiTestSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logos/$slug': typeof ApiLogosSlugRoute
  '/_authed/connections/': typeof AuthedConnectionsIndexRoute
  '/_authed/memories/': typeof AuthedMemoriesIndexRoute
  '/_authed/memories/$memory_id/': typeof AuthedMemoriesMemory_idIndexRoute
  '/_authed/memories/new/': typeof AuthedMemoriesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/.well-known/$'
    | '/consent'
    | '/sign-in'
    | '/mcp/'
    | '/notes-ui-test/$'
    | '/api/auth/$'
    | '/api/logos/$slug'
    | '/connections/'
    | '/memories/'
    | '/memories/$memory_id/'
    | '/memories/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/.well-known/$'
    | '/consent'
    | '/sign-in'
    | '/mcp'
    | '/notes-ui-test/$'
    | '/api/auth/$'
    | '/api/logos/$slug'
    | '/connections'
    | '/memories'
    | '/memories/$memory_id'
    | '/memories/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/.well-known/$'
    | '/_public/consent'
    | '/_public/sign-in'
    | '/mcp/'
    | '/_authed/notes-ui-test/$'
    | '/api/auth/$'
    | '/api/logos/$slug'
    | '/_authed/connections/'
    | '/_authed/memories/'
    | '/_authed/memories/$memory_id/'
    | '/_authed/memories/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  PublicConsentRoute: typeof PublicConsentRoute
  PublicSignInRoute: typeof PublicSignInRoute
  McpIndexRoute: typeof McpIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLogosSlugRoute: typeof ApiLogosSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/consent': {
      id: '/_public/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof PublicConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/connections/': {
      id: '/_authed/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthedConnectionsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/memories/': {
      id: '/_authed/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof AuthedMemoriesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/notes-ui-test/$': {
      id: '/_authed/notes-ui-test/$'
      path: '/notes-ui-test/$'
      fullPath: '/notes-ui-test/$'
      preLoaderRoute: typeof AuthedNotesUiTestSplatRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logos/$slug': {
      id: '/api/logos/$slug'
      path: '/api/logos/$slug'
      fullPath: '/api/logos/$slug'
      preLoaderRoute: typeof ApiLogosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/memories/$memory_id/': {
      id: '/_authed/memories/$memory_id/'
      path: '/memories/$memory_id'
      fullPath: '/memories/$memory_id/'
      preLoaderRoute: typeof AuthedMemoriesMemory_idIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/memories/new/': {
      id: '/_authed/memories/new/'
      path: '/memories/new'
      fullPath: '/memories/new/'
      preLoaderRoute: typeof AuthedMemoriesNewIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedNotesUiTestSplatRoute: typeof AuthedNotesUiTestSplatRoute
  AuthedConnectionsIndexRoute: typeof AuthedConnectionsIndexRoute
  AuthedMemoriesIndexRoute: typeof AuthedMemoriesIndexRoute
  AuthedMemoriesMemory_idIndexRoute: typeof AuthedMemoriesMemory_idIndexRoute
  AuthedMemoriesNewIndexRoute: typeof AuthedMemoriesNewIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedNotesUiTestSplatRoute: AuthedNotesUiTestSplatRoute,
  AuthedConnectionsIndexRoute: AuthedConnectionsIndexRoute,
  AuthedMemoriesIndexRoute: AuthedMemoriesIndexRoute,
  AuthedMemoriesMemory_idIndexRoute: AuthedMemoriesMemory_idIndexRoute,
  AuthedMemoriesNewIndexRoute: AuthedMemoriesNewIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  PublicConsentRoute: PublicConsentRoute,
  PublicSignInRoute: PublicSignInRoute,
  McpIndexRoute: McpIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLogosSlugRoute: ApiLogosSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
